server:
  port: 8094

spring:
  application:
    name: account-service
  data:
    mongodb:
      database: db_account
      uri: mongodb://localhost:27017/account
  kafka:
    bootstrap-server: ${kafka.server.hostname}:${kafka.server.port}
    
kafka:
  server:
    hostname: localhost
    port: 9092
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
            
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 2s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - java.net.ConnectException
    instances:
      accountServiceCircuitBreaker:
        baseConfig: default
